In [63]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [64]:
bgg_data = pd.DataFrame()
json_test = pd.read_json('data/batches/bgg_batch_test.json')
json_test.head()

,row_id,type,boardgame,description,min_players,max_players,suggested_numplayers,min_playtime,max_playtime,playingtime,...,categories,mechanisms,family,designers,artists,publishers,owned,trading,wanting,wishing
0,224517,boardgame,Brass: Birmingham,Brass: Birmingham is an economic strategy game...,2,4,"{'Best': '4', 'Recommended': '2', 'Not Recomme...",60,120,120,...,"[Age of Reason, Economic, Industry / Manufactu...","[Chaining, End Game Bonuses, Hand Management, ...","[Cities: Birmingham (England), Components: Map...","[Gavan Brown, Matt Tolman, Martin Wallace]","[Gavan Brown, Lina Cossette, David Forest, Gui...","[Roxley, Arclight Games, Board Game Rookie, Bo...",83744,367,1754,21874
1,342942,boardgame,Ark Nova,"In Ark Nova, you will plan and design a modern...",1,4,"{'Best': '2', 'Recommended': '3', 'Not Recomme...",90,150,150,...,"[Animals, Card Game, Environmental]","[Contracts, End Game Bonuses, Events, Grid Cov...","[Animals: Okapi, Components: Hexagonal Tiles, ...",[Mathias Wigge],"[Steffen Bieker, Loïc Billiau, Dennis Lohausen]","[Feuerland Spiele, Capstone Games, CMON Global...",88580,447,1071,17713
2,161936,boardgame,Pandemic Legacy: Season 1,Pandemic Legacy is a co-operative campaign gam...,2,4,"{'Best': '4', 'Recommended': '2', 'Not Recomme...",60,60,60,...,"[Environmental, Medical]","[Action Points, Cooperative Game, Hand Managem...","[Components: Map (Global Scale), Components: M...","[Rob Daviau, Matt Leacock]",[Chris Quilliams],"[Z-Man Games, Asterion Press, Devir, Filosofia...",89321,524,807,15019
3,174430,boardgame,Gloomhaven,Gloomhaven is a game of Euro-inspired tactica...,1,4,"{'Best': '3', 'Recommended': '2', 'Not Recomme...",60,120,120,...,"[Adventure, Exploration, Fantasy, Fighting, Mi...","[Action Queue, Action Retrieval, Campaign / Ba...","[Category: Dungeon Crawler, Components: Map (C...",[Isaac Childres],"[Alexandr Elichev, Lucile Mathieu, Josh T. McD...","[Cephalofair Games, Albi, Albi Polska, Arcligh...",104470,1306,1158,22286
4,397598,boardgame,Dune: Imperium – Uprising,"In Dune: Imperium Uprising, you want to contin...",1,6,"{'Best': '4', 'Recommended': '3', 'Not Recomme...",60,120,120,...,"[Movies / TV / Radio theme, Novel-based, Scien...","[Automatic Resource Growth, Card Play Conflict...","[Books: Dune, Game: Dune: Imperium, Misc: Long...",[Paul Dennen],"[Clay Brooks, Derek Herring, Raul Ramos, Nate ...","[Dire Wolf, Arclight Games, Broadway Toys LTD,...",28205,82,886,7794

In [65]:
json_test.info()
json_test.describe()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 30 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   row_id                500 non-null    int64
 1   type                  500 non-null    str
 2   boardgame             500 non-null    str
 3   description           500 non-null    str
 4   min_players           500 non-null    int64
 5   max_players           500 non-null    int64
 6   suggested_numplayers  500 non-null    object
 7   min_playtime          500 non-null    int64
 8   max_playtime          500 non-null    int64
 9   playingtime           500 non-null    int64
 10  minimum_age           500 non-null    int64
 11  release_year          500 non-null    int64
 12  average_rating        500 non-null    float64
 13  num_of_ratings        500 non-null    int64
 14  weight                500 non-null    float64
 15  num_of_weights        500 non-null    int64
 16  bayes_average         500 non-null    float64
 17  std_deviation         500 non-null    float64
 18  ranks                 500 non-null    object
 19  language_dependency   500 non-null    str
 20  categories            500 non-null    object
 21  mechanisms            500 non-null    object
 22  family                500 non-null    object
 23  designers             500 non-null    object
 24  artists               500 non-null    object
 25  publishers            500 non-null    object
 26  owned                 500 non-null    int64
 27  trading               500 non-null    int64
 28  wanting               500 non-null    int64
 29  wishing               500 non-null    int64
dtypes: float64(4), int64(14), object(8), str(4)
memory usage: 117.3+ KB

,row_id,min_players,max_players,min_playtime,max_playtime,playingtime,minimum_age,release_year,average_rating,num_of_ratings,weight,num_of_weights,bayes_average,std_deviation,owned,trading,wanting,wishing
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.0000,500.000000,500.00000,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000
mean,206622.038000,1.688000,5.098000,59.954000,101.894000,101.894000,12.068000,2005.872000,7.772146,21589.3140,2.841804,900.19200,7.352590,1.353060,32762.030000,416.56200,606.934000,5745.334000
std,119591.036322,0.718114,7.584685,40.004958,88.509653,88.509653,2.089044,190.252231,0.337740,20725.2239,0.826739,1041.86698,0.294669,0.159806,31367.469871,382.57295,338.398903,4054.006452
min,3.000000,1.000000,1.000000,0.000000,0.000000,0.000000,6.000000,-2200.000000,7.113910,2499.0000,1.019700,51.00000,7.003110,1.077870,5423.000000,15.00000,41.000000,483.000000
25%,124085.750000,1.000000,4.000000,30.000000,50.000000,50.000000,10.000000,2012.000000,7.526508,8817.0000,2.230875,303.00000,7.109413,1.228563,13460.750000,164.75000,371.000000,3103.750000
50%,216752.000000,2.000000,4.000000,60.000000,90.000000,90.000000,12.000000,2017.000000,7.721860,14853.0000,2.874550,524.50000,7.272275,1.331225,22587.500000,303.00000,533.500000,4529.000000
75%,299824.750000,2.000000,5.000000,80.000000,120.000000,120.000000,14.000000,2021.000000,7.981743,25399.2500,3.456350,1069.75000,7.527010,1.443130,38920.000000,527.75000,751.750000,6947.000000
max,454103.000000,6.000000,100.000000,480.000000,1200.000000,1200.000000,18.000000,2025.000000,9.008100,139626.0000,4.646100,8634.00000,8.393530,2.012270,225741.000000,3351.00000,1977.000000,27010.000000

In [68]:
json_test['release_year'] = pd.to_numeric(json_test['release_year'], errors='coerce')
json_test['min_players'] = pd.to_numeric(json_test['min_players'], errors='coerce')
json_test['max_players'] = pd.to_numeric(json_test['max_players'], errors='coerce')
json_test['min_playtime'] = pd.to_numeric(json_test['min_playtime'], errors='coerce')
json_test['max_playtime'] = pd.to_numeric(json_test['max_playtime'], errors='coerce')
json_test['playingtime'] = pd.to_numeric(json_test['playingtime'], errors='coerce')
json_test['minimum_age'] = pd.to_numeric(json_test['minimum_age'], errors='coerce')
json_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 30 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   row_id                500 non-null    int64
 1   type                  500 non-null    str
 2   boardgame             500 non-null    str
 3   description           500 non-null    str
 4   min_players           500 non-null    int64
 5   max_players           500 non-null    int64
 6   suggested_numplayers  500 non-null    object
 7   min_playtime          500 non-null    int64
 8   max_playtime          500 non-null    int64
 9   playingtime           500 non-null    int64
 10  minimum_age           500 non-null    int64
 11  release_year          500 non-null    int64
 12  average_rating        500 non-null    float64
 13  num_of_ratings        500 non-null    int64
 14  weight                500 non-null    float64
 15  num_of_weights        500 non-null    int64
 16  bayes_average         500 non-null    float64
 17  std_deviation         500 non-null    float64
 18  ranks                 500 non-null    object
 19  language_dependency   500 non-null    str
 20  categories            500 non-null    object
 21  mechanisms            500 non-null    object
 22  family                500 non-null    object
 23  designers             500 non-null    object
 24  artists               500 non-null    object
 25  publishers            500 non-null    object
 26  owned                 500 non-null    int64
 27  trading               500 non-null    int64
 28  wanting               500 non-null    int64
 29  wishing               500 non-null    int64
dtypes: float64(4), int64(14), object(8), str(4)
memory usage: 117.3+ KB